import { IProject } from "../types";

export const projectsList: IProject[] = [
export const projectsList: IProject[] = [
    {
        id: "1",
        name: "Project Management SAAS Landing Page",
        bigDescription: "A landing page for a project management SAAS application.",
        tools: ["framer"],
        gradient: "gradient-1",
        mainImage: "social-media-app.png",
        type: "noCode",
        demo: "https://example-social-media-app.com",
        github: "https://github.com/example-social-media-app",
        smallDescription: "A landing page for a project management SAAS application.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: ["project_management.jpg"],
        ready: true,
    },
    {
        id: "2",
        name: "Digital Agency Landing Page",
        bigDescription: "A landing page for a digital agency.",
        tools: ["framer"],
        gradient: "gradient-2",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "A landing page for a digital agency.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "3",
        name: "Software Website",
        bigDescription: "Software website for a software company.",
        tools: ["framer"],
        gradient: "gradient-3",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "4",
        name: "Agency Landing page",
        bigDescription: "Software website for a software company.",
        tools: ["framer"],
        gradient: "gradient-4",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "5",
        name: "Finance Landing page",
        bigDescription: "Software website for a software company.",
        tools: ["framer"],
        gradient: "gradient-5",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "6",
        name: "Website Development Agency",
        bigDescription: "Software website for a software company.",
        tools: ["framer"],
        gradient: "gradient-6",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "7",
        name: "Mobile App Landing Page",
        bigDescription: "Software website for a software company.",
        tools: ["framer"],
        gradient: "gradient-7",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "8",
        name: "Portfolio",
        bigDescription: "Software website for a software company.",
        tools: ["framer"],
        gradient: "gradient-8",
        mainImage: "",
        type: "noCode",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    // Software Projects
    {
        id: "9",
        name: "Advanced Calculator",
        bigDescription: "Software website for a software company.",
        tools: ["python"],
        gradient: "gradient-10",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "10",
        name: "Password Generator",
        bigDescription: "Software website for a software company.",
        tools: ["python"],
        gradient: "gradient-11",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "11",
        name: "Snake Game",
        bigDescription: "Software website for a software company.",
        tools: ["python"],
        gradient: "gradient-12",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "12",
        name: "Tic Tac Toe",
        bigDescription: "Software website for a software company.",
        tools: ["python"],
        gradient: "gradient-13",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "13",
        name: "Text Editor",
        bigDescription: "Software website for a software company.",
        tools: ["csharp"],
        gradient: "gradient-1",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "14",
        name: "Web Browser",
        bigDescription: "Software website for a software company.",
        tools: ["java"],
        gradient: "gradient-3",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "15",
        name: "Music Player",
        bigDescription: "Software website for a software company.",
        tools: ["java"],
        gradient: "gradient-5",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "16",
        name: "Video Player",
        bigDescription: "Software website for a software company.",
        tools: ["java"],
        gradient: "gradient-7",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Python", "Tkinter", "Random"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "17",
        name: "Image Viewer",
        bigDescription: "Software website for a software company.",
        tools: ["java"],
        gradient: "gradient-13",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Java", "Swing", "AWT"],
        screenshots: [""],
        ready: false,
    },
    {
        id: "18",
        name: "Whiteboard",
        bigDescription: "Software website for a software company.",
        tools: ["java"],
        gradient: "gradient-12",
        mainImage: "",
        type: "software",
        demo: "",
        github: "",
        smallDescription: "Software website for a software company.",
        highlights: ["Java", "Swing", "AWT"],
        screenshots: [""],
        ready: false,
    },
];
