import { IProject } from "../types";

export const projectsList: IProject[] = [
    {
        id: "1",
        name: "Project Management SAAS Landing Page",
        bigDescription:
            "A landing page for a project management SAAS application. It showcases the features and benefits of the SAAS platform, including task management, team collaboration, and project tracking. The landing page is designed to attract potential users and provide them with a clear understanding of the value proposition of the application. It features a modern and responsive design, with intuitive navigation and visually appealing elements. The landing page also includes testimonials from satisfied users and a call-to-action to encourage visitors to sign up for a free trial or request a demo.",
        tools: ["framer", "figma", "react", "tailwind", "angular", "svelte", "vue", "typescript"],
        gradient: "gradient-1",
        mainImage: "social-media-app.png",
        type: "uiDesign",
        demo: "https://example-social-media-app.com",
        github: "https://github.com/example-social-media-app",
        smallDescription:
            "A landing page for a project management SAAS application. It showcases the features and benefits of the SAAS platform, including task management.",

        highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
        screenshots: [""],
        ready: true,
        colors: [
            {
                title: "Primary",
                shades: [
                    { color: "#F0FFF4", shade: "50" },
                    { color: "#C6F6D5", shade: "100" },
                    { color: "#9AE6B4", shade: "200" },
                    { color: "#68D391", shade: "300" },
                    { color: "#48BB78", shade: "400" },
                    { color: "#38A169", shade: "500" },
                    { color: "#2F855A", shade: "600" },
                    { color: "#276749", shade: "700" },
                    { color: "#22543D", shade: "800" },
                ],
            },
            {
                title: "Secondary",
                shades: [
                    { color: "#F0F4FF", shade: "50" },
                    { color: "#C3DAFE", shade: "100" },
                    { color: "#A3BFFA", shade: "200" },
                    { color: "#7F9CF5", shade: "300" },
                    { color: "#667EEA", shade: "400" },
                    { color: "#5A67D8", shade: "500" },
                    { color: "#4C51BF", shade: "600" },
                    { color: "#434190", shade: "700" },
                    { color: "#3C366B", shade: "800" },
                ],
            },
        ],
        types: [
            {
                title: "Heading 1",
                fontSize: "36px",
                lineHeight: "48px",
                fontWeight: "700",
                fontFamily: "Inter",
            },
            {
                title: "Heading 2",
                fontSize: "24px",
                lineHeight: "36px",
                fontWeight: "600",
                fontFamily: "Inter",
            },
            {
                title: "Body",
                fontSize: "16px",
                lineHeight: "24px",
                fontWeight: "400",
                fontFamily: "Inter",
            },
        ],
        icons: [
            {
                title: "Icon 1",
                path: "C:\\Users\\alexs\\Desktop\\search.svg",
            },
        ],
    },
    // },
    // {
    //     id: "2",
    //     name: "Digital Agency Landing Page",
    //     bigDescription: "A landing page for a digital agency.",
    //     tools: ["framer"],
    //     gradient: "gradient-2",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "A landing page for a digital agency.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "3",
    //     name: "Software Website",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["framer"],
    //     gradient: "gradient-3",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "4",
    //     name: "Agency Landing page",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["framer"],
    //     gradient: "gradient-4",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "5",
    //     name: "Finance Landing page",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["framer"],
    //     gradient: "gradient-5",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "6",
    //     name: "Website Development Agency",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["framer"],
    //     gradient: "gradient-6",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "7",
    //     name: "Mobile App Landing Page",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["framer"],
    //     gradient: "gradient-7",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "8",
    //     name: "Portfolio",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["framer"],
    //     gradient: "gradient-8",
    //     mainImage: "",
    //     type: "noCode",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // // Software Projects
    // {
    //     id: "9",
    //     name: "Advanced Calculator",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["python"],
    //     gradient: "gradient-10",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["React", "Node.js", "MongoDB", "Express", "RESTful API", "Authentication"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "10",
    //     name: "Password Generator",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["python"],
    //     gradient: "gradient-11",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "11",
    //     name: "Snake Game",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["python"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "12",
    //     name: "Tic Tac Toe",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["python"],
    //     gradient: "gradient-13",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "13",
    //     name: "Text Editor",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["csharp"],
    //     gradient: "gradient-1",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "14",
    //     name: "Web Browser",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["java"],
    //     gradient: "gradient-3",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "15",
    //     name: "Music Player",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["java"],
    //     gradient: "gradient-5",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "16",
    //     name: "Video Player",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["java"],
    //     gradient: "gradient-7",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Python", "Tkinter", "Random"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "17",
    //     name: "Image Viewer",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["java"],
    //     gradient: "gradient-13",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "18",
    //     name: "Whiteboard",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["java"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "software",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "19",
    //     name: "Content Marketing Software",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["figma", "angular", "react", "svelte", "vue", "tailwind"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "uiDesign",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "20",
    //     name: "Restaurant Website",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["figma", "angular", "react", "svelte", "vue", "tailwind"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "frontend",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "21",
    //     name: "Event Website",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["figma", "angular", "react", "svelte", "vue", "tailwind"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "frontend",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "22",
    //     name: "Furniture Website",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["figma", "angular", "react", "svelte", "vue", "tailwind"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "frontend",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "23",
    //     name: "Landing page dashboard",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["figma", "angular", "react", "svelte", "vue", "tailwind"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "frontend",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
    // {
    //     id: "24",
    //     name: "Social markiting website",
    //     bigDescription: "Software website for a software company.",
    //     tools: ["figma", "angular", "react", "svelte", "vue", "tailwind"],
    //     gradient: "gradient-12",
    //     mainImage: "",
    //     type: "frontend",
    //     demo: "",
    //     github: "",
    //     smallDescription: "Software website for a software company.",
    //     highlights: ["Java", "Swing", "AWT"],
    //     screenshots: [""],
    //     ready: false,
    // },
];
